title: "Dango Bites"
description: "Exploring Japan in bite sized portions"
theme: minima

# GitHub Pages settings
url: "https://kingwoodbud0.github.io"
baseurl: "/Japan"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
